### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by cpsdqs** [cpsdqs/Phage#1]
- [x] Disabling bundles
- [ ] UserCSS (esp. preprocessors)
- [ ] @‌run-at
- [ ] Inject stylesheets on sites with CSP by using document.styleSheets/constructible stylesheets in the future
- [ ] Bundle management (add, edit files with `open`, drag & drop)
- [ ] Per-script (per-bundle?) error log
- [ ] “Scripts on this page” in popover
- [ ] GM API for userscripts
- [ ] Namespaces (esp. regarding @‌require)
